---
title: "CoverPage"
author: "steppe"
date: "2024-03-03"
output: pdf_document
---

**Authors and Affiliations:**    
Reed Clark Benkendorf^1,2^       
Emily J. Woodworth^1,2^       
Paul J. CaraDonna^1,2,3^      
Jane E. Ogilvie^3^      
Sophie Taddeo^1,2,4^      
Jeremie B. Fant^1,2^     

**Addresses:**      
^1^ Chicago Botanic Garden, Glencoe, Illinois 60022, USA    
^2^ Plant Biology and Conservation, Northwestern University, Evanston, Illinois 60208, USA    
^3^ Rocky Mountain Biological Laboratory, P.O. Box 519, Crested Butte, Colorado 81224, USA    
^4^ Department of Environmental and Ocean Sciences, University of San Diego, San Diego, USA   

**Acknowledgements** The authors would like to sincerely thank N. Zerega, P. Herendeen, H. Noble, A. McDonnell, and E. Loke for their assistance with acquiring herbarium loans, pollen identification, and preparing the genomic libraries;; I. Breckheimer for sharing spatial data;; herbarium curators B. Legler, R. Williams, E. Nelson;; and J. Reitheel and staff at the the RMBL for access to field sites and logistical support.

**Author Contributions**  R.C.B, J.O., J.B.F, S.T. conceived the ideas and designed methodology; J.O., P.J.C., R.C.B. and E.J.W. collected the data; R.C.B. analysed the data. All authors contributed critically to the drafts and gave final approval for publication.

*Data Availability Statements* The queries required to download all data used in this project are located in… All novel sequencing data are located at NCBI…


            A concise and informative title. Do not include the authorities for taxonomic names.
            A list of all authors' names with names and addresses of Institutions.
            The name, address and e-mail address of the correspondence author.
            A running headline of not more than 45 characters.
            Acknowledgments, data availability, conflict of interest and author contribution statements.
